"""Add inspection history table

Revision ID: 5cd42af34616
Revises: a77c82cbb191
Create Date: 2025-12-19 14:44:09.736037

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cd42af34616"
down_revision: Union[str, Sequence[str], None] = "a77c82cbb191"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inspection_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("sku_code", sa.String(length=50), nullable=False),
        sa.Column("image_filename", sa.String(length=500), nullable=False),
        sa.Column("image_path", sa.String(length=1000), nullable=True),
        sa.Column("judgment", sa.Enum("OK", "OK_WITH_WARNING", "NG", "RETAKE", name="judgmenttype"), nullable=False),
        sa.Column("overall_delta_e", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("zones_count", sa.Integer(), nullable=False),
        sa.Column("analysis_result", sa.JSON(), nullable=False),
        sa.Column("ng_reasons", sa.JSON(), nullable=True),
        sa.Column("retake_reasons", sa.JSON(), nullable=True),
        sa.Column("decision_trace", sa.JSON(), nullable=True),
        sa.Column("next_actions", sa.JSON(), nullable=True),
        sa.Column("lens_detected", sa.Integer(), nullable=False),
        sa.Column("lens_confidence", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("operator", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column("has_warnings", sa.Integer(), nullable=False),
        sa.Column("has_ink_analysis", sa.Integer(), nullable=False),
        sa.Column("has_radial_profile", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_inspection_confidence", "inspection_history", ["confidence"], unique=False)
    op.create_index("idx_inspection_created", "inspection_history", ["created_at"], unique=False)
    op.create_index("idx_inspection_delta_e", "inspection_history", ["overall_delta_e"], unique=False)
    op.create_index("idx_inspection_sku_judgment", "inspection_history", ["sku_code", "judgment"], unique=False)
    op.create_index(op.f("ix_inspection_history_created_at"), "inspection_history", ["created_at"], unique=False)
    op.create_index(op.f("ix_inspection_history_judgment"), "inspection_history", ["judgment"], unique=False)
    op.create_index(
        op.f("ix_inspection_history_overall_delta_e"), "inspection_history", ["overall_delta_e"], unique=False
    )
    op.create_index(op.f("ix_inspection_history_session_id"), "inspection_history", ["session_id"], unique=True)
    op.create_index(op.f("ix_inspection_history_sku_code"), "inspection_history", ["sku_code"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inspection_history_sku_code"), table_name="inspection_history")
    op.drop_index(op.f("ix_inspection_history_session_id"), table_name="inspection_history")
    op.drop_index(op.f("ix_inspection_history_overall_delta_e"), table_name="inspection_history")
    op.drop_index(op.f("ix_inspection_history_judgment"), table_name="inspection_history")
    op.drop_index(op.f("ix_inspection_history_created_at"), table_name="inspection_history")
    op.drop_index("idx_inspection_sku_judgment", table_name="inspection_history")
    op.drop_index("idx_inspection_delta_e", table_name="inspection_history")
    op.drop_index("idx_inspection_created", table_name="inspection_history")
    op.drop_index("idx_inspection_confidence", table_name="inspection_history")
    op.drop_table("inspection_history")
    # ### end Alembic commands ###
