"""Add profile_score to ComparisonResult

Revision ID: a77c82cbb191
Revises: e377e0730c8c
Create Date: 2025-12-18 21:44:49.715853

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a77c82cbb191"
down_revision: Union[str, Sequence[str], None] = "e377e0730c8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comparison_results", sa.Column("profile_score", sa.Float(), nullable=False, server_default="0.0"))
    op.add_column("comparison_results", sa.Column("profile_details", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comparison_results", "profile_details")
    op.drop_column("comparison_results", "profile_score")
    # ### end Alembic commands ###
