"""Initial schema

Revision ID: e377e0730c8c
Revises:
Create Date: 2025-12-18 10:44:17.021839

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e377e0730c8c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "std_models",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sku_code", sa.String(length=50), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("n_samples", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("approved_by", sa.String(length=100), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku_code", "version", name="uq_sku_version"),
    )
    op.create_index("idx_std_active", "std_models", ["sku_code", "is_active"], unique=False)
    op.create_index(op.f("ix_std_models_is_active"), "std_models", ["is_active"], unique=False)
    op.create_index(op.f("ix_std_models_sku_code"), "std_models", ["sku_code"], unique=False)
    op.create_table(
        "test_samples",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sku_code", sa.String(length=50), nullable=False),
        sa.Column("batch_number", sa.String(length=50), nullable=True),
        sa.Column("sample_id", sa.String(length=100), nullable=True),
        sa.Column("image_path", sa.String(length=500), nullable=False),
        sa.Column("analysis_result", sa.JSON(), nullable=False),
        sa.Column("lens_detected", sa.Boolean(), nullable=False),
        sa.Column("lens_detection_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("operator", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("image_width", sa.Integer(), nullable=True),
        sa.Column("image_height", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_test_sample_created", "test_samples", ["created_at"], unique=False)
    op.create_index("idx_test_sample_sku_batch", "test_samples", ["sku_code", "batch_number"], unique=False)
    op.create_index(op.f("ix_test_samples_batch_number"), "test_samples", ["batch_number"], unique=False)
    op.create_index(op.f("ix_test_samples_created_at"), "test_samples", ["created_at"], unique=False)
    op.create_index(op.f("ix_test_samples_sample_id"), "test_samples", ["sample_id"], unique=True)
    op.create_index(op.f("ix_test_samples_sku_code"), "test_samples", ["sku_code"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("role", sa.Enum("ADMIN", "ENGINEER", "INSPECTOR", "VIEWER", name="userrole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=True),
        sa.Column("last_failed_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_role_active", "users", ["role", "is_active"], unique=False)
    op.create_index("idx_user_username", "users", ["username"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_action_created", "audit_logs", ["action", "created_at"], unique=False)
    op.create_index("idx_audit_target", "audit_logs", ["target_type", "target_id"], unique=False)
    op.create_index("idx_audit_user_created", "audit_logs", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_success"), "audit_logs", ["success"], unique=False)
    op.create_index(op.f("ix_audit_logs_target_id"), "audit_logs", ["target_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_target_type"), "audit_logs", ["target_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "comparison_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("test_sample_id", sa.Integer(), nullable=False),
        sa.Column("std_model_id", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("zone_score", sa.Float(), nullable=False),
        sa.Column("ink_score", sa.Float(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column(
            "judgment", sa.Enum("PASS", "FAIL", "RETAKE", "MANUAL_REVIEW", name="judgmentstatus"), nullable=False
        ),
        sa.Column("top_failure_reasons", sa.JSON(), nullable=True),
        sa.Column("defect_classifications", sa.JSON(), nullable=True),
        sa.Column("zone_details", sa.JSON(), nullable=True),
        sa.Column("ink_details", sa.JSON(), nullable=True),
        sa.Column("alignment_details", sa.JSON(), nullable=True),
        sa.Column("worst_case_metrics", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["std_model_id"],
            ["std_models.id"],
        ),
        sa.ForeignKeyConstraint(["test_sample_id"], ["test_samples.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_comparison_created", "comparison_results", ["created_at"], unique=False)
    op.create_index("idx_comparison_judgment", "comparison_results", ["judgment"], unique=False)
    op.create_index("idx_comparison_score", "comparison_results", ["total_score"], unique=False)
    op.create_index("idx_comparison_std", "comparison_results", ["std_model_id"], unique=False)
    op.create_index(op.f("ix_comparison_results_created_at"), "comparison_results", ["created_at"], unique=False)
    op.create_index(op.f("ix_comparison_results_judgment"), "comparison_results", ["judgment"], unique=False)
    op.create_index(op.f("ix_comparison_results_std_model_id"), "comparison_results", ["std_model_id"], unique=False)
    op.create_index(
        op.f("ix_comparison_results_test_sample_id"), "comparison_results", ["test_sample_id"], unique=False
    )
    op.create_index(op.f("ix_comparison_results_total_score"), "comparison_results", ["total_score"], unique=False)
    op.create_table(
        "std_samples",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("std_model_id", sa.Integer(), nullable=False),
        sa.Column("sample_index", sa.Integer(), nullable=False),
        sa.Column("image_path", sa.String(length=500), nullable=False),
        sa.Column("analysis_result", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("image_width", sa.Integer(), nullable=True),
        sa.Column("image_height", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["std_model_id"], ["std_models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("std_model_id", "sample_index", name="uq_std_sample_index"),
    )
    op.create_index("idx_std_sample_model", "std_samples", ["std_model_id", "sample_index"], unique=False)
    op.create_index(op.f("ix_std_samples_std_model_id"), "std_samples", ["std_model_id"], unique=False)
    op.create_table(
        "std_statistics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("std_model_id", sa.Integer(), nullable=False),
        sa.Column("zone_name", sa.String(length=20), nullable=False),
        sa.Column("mean_L", sa.Float(), nullable=True),
        sa.Column("std_L", sa.Float(), nullable=True),
        sa.Column("mean_a", sa.Float(), nullable=True),
        sa.Column("std_a", sa.Float(), nullable=True),
        sa.Column("mean_b", sa.Float(), nullable=True),
        sa.Column("std_b", sa.Float(), nullable=True),
        sa.Column("mean_position", sa.Float(), nullable=True),
        sa.Column("std_position", sa.Float(), nullable=True),
        sa.Column("percentile_5", sa.Float(), nullable=True),
        sa.Column("percentile_95", sa.Float(), nullable=True),
        sa.Column("max_delta_e", sa.Float(), nullable=True),
        sa.Column("tolerance_position", sa.Float(), nullable=True),
        sa.Column("detailed_stats", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["std_model_id"], ["std_models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("std_model_id", "zone_name", name="uq_std_stat_zone"),
    )
    op.create_index("idx_std_stat_lab", "std_statistics", ["mean_L", "mean_a", "mean_b"], unique=False)
    op.create_index("idx_std_stat_model_zone", "std_statistics", ["std_model_id", "zone_name"], unique=False)
    op.create_index(op.f("ix_std_statistics_std_model_id"), "std_statistics", ["std_model_id"], unique=False)
    op.create_index(op.f("ix_std_statistics_zone_name"), "std_statistics", ["zone_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_std_statistics_zone_name"), table_name="std_statistics")
    op.drop_index(op.f("ix_std_statistics_std_model_id"), table_name="std_statistics")
    op.drop_index("idx_std_stat_model_zone", table_name="std_statistics")
    op.drop_index("idx_std_stat_lab", table_name="std_statistics")
    op.drop_table("std_statistics")
    op.drop_index(op.f("ix_std_samples_std_model_id"), table_name="std_samples")
    op.drop_index("idx_std_sample_model", table_name="std_samples")
    op.drop_table("std_samples")
    op.drop_index(op.f("ix_comparison_results_total_score"), table_name="comparison_results")
    op.drop_index(op.f("ix_comparison_results_test_sample_id"), table_name="comparison_results")
    op.drop_index(op.f("ix_comparison_results_std_model_id"), table_name="comparison_results")
    op.drop_index(op.f("ix_comparison_results_judgment"), table_name="comparison_results")
    op.drop_index(op.f("ix_comparison_results_created_at"), table_name="comparison_results")
    op.drop_index("idx_comparison_std", table_name="comparison_results")
    op.drop_index("idx_comparison_score", table_name="comparison_results")
    op.drop_index("idx_comparison_judgment", table_name="comparison_results")
    op.drop_index("idx_comparison_created", table_name="comparison_results")
    op.drop_table("comparison_results")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_target_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_target_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_success"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index("idx_audit_user_created", table_name="audit_logs")
    op.drop_index("idx_audit_target", table_name="audit_logs")
    op.drop_index("idx_audit_action_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("idx_user_username", table_name="users")
    op.drop_index("idx_user_role_active", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_test_samples_sku_code"), table_name="test_samples")
    op.drop_index(op.f("ix_test_samples_sample_id"), table_name="test_samples")
    op.drop_index(op.f("ix_test_samples_created_at"), table_name="test_samples")
    op.drop_index(op.f("ix_test_samples_batch_number"), table_name="test_samples")
    op.drop_index("idx_test_sample_sku_batch", table_name="test_samples")
    op.drop_index("idx_test_sample_created", table_name="test_samples")
    op.drop_table("test_samples")
    op.drop_index(op.f("ix_std_models_sku_code"), table_name="std_models")
    op.drop_index(op.f("ix_std_models_is_active"), table_name="std_models")
    op.drop_index("idx_std_active", table_name="std_models")
    op.drop_table("std_models")
    # ### end Alembic commands ###
